### ISSUE TITLE
Impossible to generate tiles when not all layers have the same dimensions

### ISSUE THREAD

**Issue by arnaud-morvan** [camptocamp/tilecloud-chain#299]
Related with #283

TileStore handle x,y,z tiles with fixed values in each dimension.

TileGeneration create a MultiTileStore (which manage one TileStore for each layer) but it is not consistent if all layers do not have exactly the same dimensions.
https://github.com/alexbrault/tilecloud-chain/blob/48677e7483ec2ee5f94616cffb631c4fe325e168/tilecloud_chain/__init__.py#L565

Here the trace :
```
Traceback (most recent call last):
  File ".build/venv/bin/generate_tiles", line 11, in <module>
    load_entry_point('tilecloud-chain', 'console_scripts', 'generate_tiles')()
  File "/home/amorvan/tilecloud-chain/tilecloud_chain/generate.py", line 473, in main
    generate.gene(options, gene, options.layer)
  File "/home/amorvan/tilecloud-chain/tilecloud_chain/generate.py", line 49, in gene
    self._gene(options, gene, dimensions)
  File "/home/amorvan/tilecloud-chain/tilecloud_chain/generate.py", line 89, in _gene
    self.cache_tilestore = gene.get_tilesstore(options.cache, dimensions)
  File "/home/amorvan/tilecloud-chain/tilecloud_chain/__init__.py", line 572, in get_tilesstore
    for lname, layer in self.layers.items()
  File "/home/amorvan/tilecloud-chain/tilecloud_chain/__init__.py", line 571, in <dictcomp>
    lname: self.get_store(cache, layer, dimensions=dimensions)
  File "/home/amorvan/tilecloud-chain/tilecloud_chain/__init__.py", line 459, in get_store
    for dimension in layer['dimensions']
KeyError: 'FLOOR'
```

**Comment by arnaud-morvan** [comment]
IMHO, on a design side, dimensions names should be passed to TileStore class constructor, but dimensions values should passed to the filename method.

**Comment by sbrunner** [comment]
Patch welcome
