### ISSUE TITLE
--status to get sqs queue status is broken

### ISSUE THREAD

**Issue by ochriste** [camptocamp/tilecloud-chain#340]
```
generate_controller -c /project/tilegeneration/config.yaml --status
Traceback (most recent call last):
  File "/usr/local/bin/generate_controller", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/tilecloud_chain/controller.py", line 71, in main
    status(gene)
  File "/usr/local/lib/python3.6/site-packages/tilecloud_chain/controller.py", line 458, in status
    attributes = gene.get_sqs_queue().get_attributes()
AttributeError: 'sqs.Queue' object has no attribute 'get_attributes'
```

**Comment by fredj** [comment]
it should also be changed here:
https://github.com/camptocamp/tilecloud/blob/master/tilecloud/store/sqs.py#L14
